### ISSUE TITLE
Setup test SW analysis environment - Visual Studio w/ SonarQube

### ISSUE THREAD

**Issue by jcastle** [GSA/open-source-policy#14]
- Setup GFE, VDI, and Mac with VS Community
- Dive into SonarQube
- Cloud.gov documentation and CF CLI

**Comment by jcastle** [comment]
1. Setup SonarQube locally on Macs at home and ran code through it.  Understand use and want to get to server environment to test out, maybe Cloud.gov.
2. Moving to CheckMarx as IS wants us to look at that.  Need to consider licensing and options for use (e.g., Jenkins, local, etc.), right now only web option.

**Comment by LeoCYang** [comment]
@jcastle 

FYI.  Our team uses Visual Studio 2015 Pro's built-in Code Analysis (see the attached screenshot).  It's not mandatory for my development team to use it at this point.  Some developers use it, and some don't.  I think it's a good practice to use the built-in Code Analysis to perform to static code analysis during the build.    

![vs_2015_code_analysis](https://user-images.githubusercontent.com/21242678/29627212-f4eebcc0-87f6-11e7-901a-826d9c634f1e.jpg)
