### ISSUE TITLE
Determine items needed to migrate to public repo - work with developers, capture what items in code necessary

### ISSUE THREAD

**Issue by jcastle-zz** [GSA/open-source-policy#15]
- work with developers, capture what items in code necessary

**Comment by LeoCYang** [comment]
I made some progress last week.  I remove an used project from FM-VIATP repo.

**Comment by LeoCYang** [comment]
This task is completed.  The next step is to work with the developers to organize the source code.  Organizing the source code including:

1. move some of the Visual Studio projects to other repos. where they should be
2. remove unused source code
